#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuahangbanthuoc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYCUAHANG1")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHanghoa(Hanghoa instance);
    partial void UpdateHanghoa(Hanghoa instance);
    partial void DeleteHanghoa(Hanghoa instance);
    partial void InsertHoadon(Hoadon instance);
    partial void UpdateHoadon(Hoadon instance);
    partial void DeleteHoadon(Hoadon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public dbDataContext() : 
				base(global::cuahangbanthuoc.Properties.Settings.Default.QUANLYCUAHANG1ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<Hanghoa> Hanghoas
		{
			get
			{
				return this.GetTable<Hanghoa>();
			}
		}
		
		public System.Data.Linq.Table<Hoadon> Hoadons
		{
			get
			{
				return this.GetTable<Hoadon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon
	{
		
		private string _Mahd;
		
		private string _Mahang;
		
		private System.Nullable<int> _Soluongxuat;
		
		private System.Nullable<double> _Dongia;
		
		private System.Nullable<double> _ThanhTien;
		
		public ChiTietHoaDon()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahd", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Mahd
		{
			get
			{
				return this._Mahd;
			}
			set
			{
				if ((this._Mahd != value))
				{
					this._Mahd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					this._Mahang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongxuat", DbType="Int")]
		public System.Nullable<int> Soluongxuat
		{
			get
			{
				return this._Soluongxuat;
			}
			set
			{
				if ((this._Soluongxuat != value))
				{
					this._Soluongxuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Float")]
		public System.Nullable<double> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this._Dongia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hanghoa")]
	public partial class Hanghoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahang;
		
		private string _Tenhang;
		
		private string _Mancc;
		
		private string _Loaihang;
		
		private string _Size;
		
		private string _Mau;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<double> _Gianhap;
		
		private System.Nullable<double> _Giaban;
		
		private string _Trangthai;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahangChanging(string value);
    partial void OnMahangChanged();
    partial void OnTenhangChanging(string value);
    partial void OnTenhangChanged();
    partial void OnManccChanging(string value);
    partial void OnManccChanged();
    partial void OnLoaihangChanging(string value);
    partial void OnLoaihangChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnMauChanging(string value);
    partial void OnMauChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnGianhapChanging(System.Nullable<double> value);
    partial void OnGianhapChanged();
    partial void OnGiabanChanging(System.Nullable<double> value);
    partial void OnGiabanChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public Hanghoa()
		{
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tenhang
		{
			get
			{
				return this._Tenhang;
			}
			set
			{
				if ((this._Tenhang != value))
				{
					this.OnTenhangChanging(value);
					this.SendPropertyChanging();
					this._Tenhang = value;
					this.SendPropertyChanged("Tenhang");
					this.OnTenhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mancc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mancc
		{
			get
			{
				return this._Mancc;
			}
			set
			{
				if ((this._Mancc != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManccChanging(value);
					this.SendPropertyChanging();
					this._Mancc = value;
					this.SendPropertyChanged("Mancc");
					this.OnManccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loaihang", DbType="NVarChar(50)")]
		public string Loaihang
		{
			get
			{
				return this._Loaihang;
			}
			set
			{
				if ((this._Loaihang != value))
				{
					this.OnLoaihangChanging(value);
					this.SendPropertyChanging();
					this._Loaihang = value;
					this.SendPropertyChanged("Loaihang");
					this.OnLoaihangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(10)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau", DbType="NVarChar(10)")]
		public string Mau
		{
			get
			{
				return this._Mau;
			}
			set
			{
				if ((this._Mau != value))
				{
					this.OnMauChanging(value);
					this.SendPropertyChanging();
					this._Mau = value;
					this.SendPropertyChanged("Mau");
					this.OnMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gianhap", DbType="Float")]
		public System.Nullable<double> Gianhap
		{
			get
			{
				return this._Gianhap;
			}
			set
			{
				if ((this._Gianhap != value))
				{
					this.OnGianhapChanging(value);
					this.SendPropertyChanging();
					this._Gianhap = value;
					this.SendPropertyChanged("Gianhap");
					this.OnGianhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaban", DbType="Float")]
		public System.Nullable<double> Giaban
		{
			get
			{
				return this._Giaban;
			}
			set
			{
				if ((this._Giaban != value))
				{
					this.OnGiabanChanging(value);
					this.SendPropertyChanging();
					this._Giaban = value;
					this.SendPropertyChanged("Giaban");
					this.OnGiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(50)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Hanghoa", Storage="_NhaCungCap", ThisKey="Mancc", OtherKey="Mancc", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.Hanghoas.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.Hanghoas.Add(this);
						this._Mancc = value.Mancc;
					}
					else
					{
						this._Mancc = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoadon")]
	public partial class Hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahd;
		
		private string _Makh;
		
		private string _Tenkh;
		
		private string _idNguoiban;
		
		private System.Nullable<System.DateTime> _Ngaylap;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahdChanging(string value);
    partial void OnMahdChanged();
    partial void OnMakhChanging(string value);
    partial void OnMakhChanged();
    partial void OnTenkhChanging(string value);
    partial void OnTenkhChanged();
    partial void OnidNguoibanChanging(string value);
    partial void OnidNguoibanChanged();
    partial void OnNgaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapChanged();
    #endregion
		
		public Hoadon()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahd", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahd
		{
			get
			{
				return this._Mahd;
			}
			set
			{
				if ((this._Mahd != value))
				{
					this.OnMahdChanging(value);
					this.SendPropertyChanging();
					this._Mahd = value;
					this.SendPropertyChanged("Mahd");
					this.OnMahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkh", DbType="NVarChar(50)")]
		public string Tenkh
		{
			get
			{
				return this._Tenkh;
			}
			set
			{
				if ((this._Tenkh != value))
				{
					this.OnTenkhChanging(value);
					this.SendPropertyChanging();
					this._Tenkh = value;
					this.SendPropertyChanged("Tenkh");
					this.OnTenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNguoiban", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string idNguoiban
		{
			get
			{
				return this._idNguoiban;
			}
			set
			{
				if ((this._idNguoiban != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNguoibanChanging(value);
					this.SendPropertyChanging();
					this._idNguoiban = value;
					this.SendPropertyChanged("idNguoiban");
					this.OnidNguoibanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this.OnNgaylapChanging(value);
					this.SendPropertyChanging();
					this._Ngaylap = value;
					this.SendPropertyChanged("Ngaylap");
					this.OnNgaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Hoadon", Storage="_KhachHang", ThisKey="Makh", OtherKey="Makh", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.Hoadons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.Hoadons.Add(this);
						this._Makh = value.Makh;
					}
					else
					{
						this._Makh = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Hoadon", Storage="_NhanVien", ThisKey="idNguoiban", OtherKey="ID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.Hoadons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.Hoadons.Add(this);
						this._idNguoiban = value.ID;
					}
					else
					{
						this._idNguoiban = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Makh;
		
		private string _Tenkh;
		
		private string _Sdt;
		
		private string _Gioitinh;
		
		private string _Diachi;
		
		private EntitySet<Hoadon> _Hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakhChanging(string value);
    partial void OnMakhChanged();
    partial void OnTenkhChanging(string value);
    partial void OnTenkhChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    #endregion
		
		public KhachHang()
		{
			this._Hoadons = new EntitySet<Hoadon>(new Action<Hoadon>(this.attach_Hoadons), new Action<Hoadon>(this.detach_Hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkh", DbType="NVarChar(50)")]
		public string Tenkh
		{
			get
			{
				return this._Tenkh;
			}
			set
			{
				if ((this._Tenkh != value))
				{
					this.OnTenkhChanging(value);
					this.SendPropertyChanging();
					this._Tenkh = value;
					this.SendPropertyChanged("Tenkh");
					this.OnTenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(10)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(50)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Hoadon", Storage="_Hoadons", ThisKey="Makh", OtherKey="Makh")]
		public EntitySet<Hoadon> Hoadons
		{
			get
			{
				return this._Hoadons;
			}
			set
			{
				this._Hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mancc;
		
		private string _Tenncc;
		
		private string _Diachi;
		
		private string _Trangthai;
		
		private EntitySet<Hanghoa> _Hanghoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManccChanging(string value);
    partial void OnManccChanged();
    partial void OnTennccChanging(string value);
    partial void OnTennccChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._Hanghoas = new EntitySet<Hanghoa>(new Action<Hanghoa>(this.attach_Hanghoas), new Action<Hanghoa>(this.detach_Hanghoas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mancc", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mancc
		{
			get
			{
				return this._Mancc;
			}
			set
			{
				if ((this._Mancc != value))
				{
					this.OnManccChanging(value);
					this.SendPropertyChanging();
					this._Mancc = value;
					this.SendPropertyChanged("Mancc");
					this.OnManccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenncc", DbType="NVarChar(50)")]
		public string Tenncc
		{
			get
			{
				return this._Tenncc;
			}
			set
			{
				if ((this._Tenncc != value))
				{
					this.OnTennccChanging(value);
					this.SendPropertyChanging();
					this._Tenncc = value;
					this.SendPropertyChanged("Tenncc");
					this.OnTennccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(50)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Hanghoa", Storage="_Hanghoas", ThisKey="Mancc", OtherKey="Mancc")]
		public EntitySet<Hanghoa> Hanghoas
		{
			get
			{
				return this._Hanghoas;
			}
			set
			{
				this._Hanghoas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hanghoas(Hanghoa entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_Hanghoas(Hanghoa entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Hoten;
		
		private string _Gioitinh;
		
		private System.Nullable<System.DateTime> _Namsinh;
		
		private System.Nullable<int> _Socmt;
		
		private System.Nullable<int> _Sdt;
		
		private string _Diachi;
		
		private string _Chucvu;
		
		private string _Trangthai;
		
		private EntitySet<Hoadon> _Hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnNamsinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNamsinhChanged();
    partial void OnSocmtChanging(System.Nullable<int> value);
    partial void OnSocmtChanged();
    partial void OnSdtChanging(System.Nullable<int> value);
    partial void OnSdtChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public NhanVien()
		{
			this._Hoadons = new EntitySet<Hoadon>(new Action<Hoadon>(this.attach_Hoadons), new Action<Hoadon>(this.detach_Hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namsinh", DbType="Date")]
		public System.Nullable<System.DateTime> Namsinh
		{
			get
			{
				return this._Namsinh;
			}
			set
			{
				if ((this._Namsinh != value))
				{
					this.OnNamsinhChanging(value);
					this.SendPropertyChanging();
					this._Namsinh = value;
					this.SendPropertyChanged("Namsinh");
					this.OnNamsinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socmt", DbType="Int")]
		public System.Nullable<int> Socmt
		{
			get
			{
				return this._Socmt;
			}
			set
			{
				if ((this._Socmt != value))
				{
					this.OnSocmtChanging(value);
					this.SendPropertyChanging();
					this._Socmt = value;
					this.SendPropertyChanged("Socmt");
					this.OnSocmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="Int")]
		public System.Nullable<int> Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(20)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(50)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Hoadon", Storage="_Hoadons", ThisKey="ID", OtherKey="idNguoiban")]
		public EntitySet<Hoadon> Hoadons
		{
			get
			{
				return this._Hoadons;
			}
			set
			{
				this._Hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private int _Password;
		
		private string _Email;
		
		private string _Trangthai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(int value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Int NOT NULL")]
		public int Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(50)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
