#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYCUAHANG")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertDoanhthu(Doanhthu instance);
    partial void UpdateDoanhthu(Doanhthu instance);
    partial void DeleteDoanhthu(Doanhthu instance);
    partial void InsertHanghoa(Hanghoa instance);
    partial void UpdateHanghoa(Hanghoa instance);
    partial void DeleteHanghoa(Hanghoa instance);
    partial void InsertHoadon(Hoadon instance);
    partial void UpdateHoadon(Hoadon instance);
    partial void DeleteHoadon(Hoadon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CSDL.Properties.Settings.Default.QUANLYCUAHANGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<Doanhthu> Doanhthus
		{
			get
			{
				return this.GetTable<Doanhthu>();
			}
		}
		
		public System.Data.Linq.Table<Hanghoa> Hanghoas
		{
			get
			{
				return this.GetTable<Hanghoa>();
			}
		}
		
		public System.Data.Linq.Table<Hoadon> Hoadons
		{
			get
			{
				return this.GetTable<Hoadon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahd;
		
		private string _Mahang;
		
		private System.Nullable<int> _Soluongxuat;
		
		private System.Nullable<decimal> _Dongia;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<Hoadon> _Hoadon;
		
		private EntityRef<Hanghoa> _Hanghoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahdChanging(string value);
    partial void OnMahdChanged();
    partial void OnMahangChanging(string value);
    partial void OnMahangChanged();
    partial void OnSoluongxuatChanging(System.Nullable<int> value);
    partial void OnSoluongxuatChanged();
    partial void OnDongiaChanging(System.Nullable<decimal> value);
    partial void OnDongiaChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._Hoadon = default(EntityRef<Hoadon>);
			this._Hanghoa = default(EntityRef<Hanghoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahd", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahd
		{
			get
			{
				return this._Mahd;
			}
			set
			{
				if ((this._Mahd != value))
				{
					this.OnMahdChanging(value);
					this.SendPropertyChanging();
					this._Mahd = value;
					this.SendPropertyChanged("Mahd");
					this.OnMahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					if (this._Hanghoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongxuat", DbType="Int")]
		public System.Nullable<int> Soluongxuat
		{
			get
			{
				return this._Soluongxuat;
			}
			set
			{
				if ((this._Soluongxuat != value))
				{
					this.OnSoluongxuatChanging(value);
					this.SendPropertyChanging();
					this._Soluongxuat = value;
					this.SendPropertyChanged("Soluongxuat");
					this.OnSoluongxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Money")]
		public System.Nullable<decimal> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietHoaDon_Hoadon", Storage="_Hoadon", ThisKey="Mahd", OtherKey="Mahd", IsUnique=true, IsForeignKey=false)]
		public Hoadon Hoadon
		{
			get
			{
				return this._Hoadon.Entity;
			}
			set
			{
				Hoadon previousValue = this._Hoadon.Entity;
				if (((previousValue != value) 
							|| (this._Hoadon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hoadon.Entity = null;
						previousValue.ChiTietHoaDon = null;
					}
					this._Hoadon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDon = this;
					}
					this.SendPropertyChanged("Hoadon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanghoa_ChiTietHoaDon", Storage="_Hanghoa", ThisKey="Mahang", OtherKey="Mahang", IsForeignKey=true)]
		public Hanghoa Hanghoa
		{
			get
			{
				return this._Hanghoa.Entity;
			}
			set
			{
				Hanghoa previousValue = this._Hanghoa.Entity;
				if (((previousValue != value) 
							|| (this._Hanghoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hanghoa.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._Hanghoa.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._Mahang = value.Mahang;
					}
					else
					{
						this._Mahang = default(string);
					}
					this.SendPropertyChanged("Hanghoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doanhthu")]
	public partial class Doanhthu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahang;
		
		private string _Mancc;
		
		private System.Nullable<int> _SLton;
		
		private System.Nullable<decimal> _Tiennhap;
		
		private System.Nullable<decimal> _Tienban;
		
		private System.Nullable<decimal> _Doanhthu1;
		
		private EntityRef<Hanghoa> _Hanghoa;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahangChanging(string value);
    partial void OnMahangChanged();
    partial void OnManccChanging(string value);
    partial void OnManccChanged();
    partial void OnSLtonChanging(System.Nullable<int> value);
    partial void OnSLtonChanged();
    partial void OnTiennhapChanging(System.Nullable<decimal> value);
    partial void OnTiennhapChanged();
    partial void OnTienbanChanging(System.Nullable<decimal> value);
    partial void OnTienbanChanged();
    partial void OnDoanhthu1Changing(System.Nullable<decimal> value);
    partial void OnDoanhthu1Changed();
    #endregion
		
		public Doanhthu()
		{
			this._Hanghoa = default(EntityRef<Hanghoa>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					if (this._Hanghoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mancc", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Mancc
		{
			get
			{
				return this._Mancc;
			}
			set
			{
				if ((this._Mancc != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManccChanging(value);
					this.SendPropertyChanging();
					this._Mancc = value;
					this.SendPropertyChanged("Mancc");
					this.OnManccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLton", DbType="Int")]
		public System.Nullable<int> SLton
		{
			get
			{
				return this._SLton;
			}
			set
			{
				if ((this._SLton != value))
				{
					this.OnSLtonChanging(value);
					this.SendPropertyChanging();
					this._SLton = value;
					this.SendPropertyChanged("SLton");
					this.OnSLtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiennhap", DbType="Money")]
		public System.Nullable<decimal> Tiennhap
		{
			get
			{
				return this._Tiennhap;
			}
			set
			{
				if ((this._Tiennhap != value))
				{
					this.OnTiennhapChanging(value);
					this.SendPropertyChanging();
					this._Tiennhap = value;
					this.SendPropertyChanged("Tiennhap");
					this.OnTiennhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tienban", DbType="Money")]
		public System.Nullable<decimal> Tienban
		{
			get
			{
				return this._Tienban;
			}
			set
			{
				if ((this._Tienban != value))
				{
					this.OnTienbanChanging(value);
					this.SendPropertyChanging();
					this._Tienban = value;
					this.SendPropertyChanged("Tienban");
					this.OnTienbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Doanhthu", Storage="_Doanhthu1", DbType="Money")]
		public System.Nullable<decimal> Doanhthu1
		{
			get
			{
				return this._Doanhthu1;
			}
			set
			{
				if ((this._Doanhthu1 != value))
				{
					this.OnDoanhthu1Changing(value);
					this.SendPropertyChanging();
					this._Doanhthu1 = value;
					this.SendPropertyChanged("Doanhthu1");
					this.OnDoanhthu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanghoa_Doanhthu", Storage="_Hanghoa", ThisKey="Mahang", OtherKey="Mahang", IsForeignKey=true)]
		public Hanghoa Hanghoa
		{
			get
			{
				return this._Hanghoa.Entity;
			}
			set
			{
				Hanghoa previousValue = this._Hanghoa.Entity;
				if (((previousValue != value) 
							|| (this._Hanghoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hanghoa.Entity = null;
						previousValue.Doanhthu = null;
					}
					this._Hanghoa.Entity = value;
					if ((value != null))
					{
						value.Doanhthu = this;
						this._Mahang = value.Mahang;
					}
					else
					{
						this._Mahang = default(string);
					}
					this.SendPropertyChanged("Hanghoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Doanhthu", Storage="_NhaCungCap", ThisKey="Mancc", OtherKey="Mancc", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.Doanhthus.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.Doanhthus.Add(this);
						this._Mancc = value.Mancc;
					}
					else
					{
						this._Mancc = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hanghoa")]
	public partial class Hanghoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahang;
		
		private string _Tenhang;
		
		private string _LoaiHang;
		
		private string _Size;
		
		private string _Mau;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Gia;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<Doanhthu> _Doanhthu;
		
		private EntitySet<NhaCungCap> _NhaCungCaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahangChanging(string value);
    partial void OnMahangChanged();
    partial void OnTenhangChanging(string value);
    partial void OnTenhangChanged();
    partial void OnLoaiHangChanging(string value);
    partial void OnLoaiHangChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnMauChanging(string value);
    partial void OnMauChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public Hanghoa()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._Doanhthu = default(EntityRef<Doanhthu>);
			this._NhaCungCaps = new EntitySet<NhaCungCap>(new Action<NhaCungCap>(this.attach_NhaCungCaps), new Action<NhaCungCap>(this.detach_NhaCungCaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhang", DbType="NVarChar(50)")]
		public string Tenhang
		{
			get
			{
				return this._Tenhang;
			}
			set
			{
				if ((this._Tenhang != value))
				{
					this.OnTenhangChanging(value);
					this.SendPropertyChanging();
					this._Tenhang = value;
					this.SendPropertyChanged("Tenhang");
					this.OnTenhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHang", DbType="NVarChar(50)")]
		public string LoaiHang
		{
			get
			{
				return this._LoaiHang;
			}
			set
			{
				if ((this._LoaiHang != value))
				{
					this.OnLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiHang = value;
					this.SendPropertyChanged("LoaiHang");
					this.OnLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau", DbType="NVarChar(10)")]
		public string Mau
		{
			get
			{
				return this._Mau;
			}
			set
			{
				if ((this._Mau != value))
				{
					this.OnMauChanging(value);
					this.SendPropertyChanging();
					this._Mau = value;
					this.SendPropertyChanged("Mau");
					this.OnMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanghoa_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="Mahang", OtherKey="Mahang")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanghoa_Doanhthu", Storage="_Doanhthu", ThisKey="Mahang", OtherKey="Mahang", IsUnique=true, IsForeignKey=false)]
		public Doanhthu Doanhthu
		{
			get
			{
				return this._Doanhthu.Entity;
			}
			set
			{
				Doanhthu previousValue = this._Doanhthu.Entity;
				if (((previousValue != value) 
							|| (this._Doanhthu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Doanhthu.Entity = null;
						previousValue.Hanghoa = null;
					}
					this._Doanhthu.Entity = value;
					if ((value != null))
					{
						value.Hanghoa = this;
					}
					this.SendPropertyChanged("Doanhthu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanghoa_NhaCungCap", Storage="_NhaCungCaps", ThisKey="Mahang", OtherKey="Mahang")]
		public EntitySet<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this._NhaCungCaps;
			}
			set
			{
				this._NhaCungCaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Hanghoa = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Hanghoa = null;
		}
		
		private void attach_NhaCungCaps(NhaCungCap entity)
		{
			this.SendPropertyChanging();
			entity.Hanghoa = this;
		}
		
		private void detach_NhaCungCaps(NhaCungCap entity)
		{
			this.SendPropertyChanging();
			entity.Hanghoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoadon")]
	public partial class Hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahd;
		
		private string _Makh;
		
		private string _Tenkh;
		
		private string _idNguoiban;
		
		private System.Nullable<System.DateTime> _Ngaylap;
		
		private EntityRef<ChiTietHoaDon> _ChiTietHoaDon;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahdChanging(string value);
    partial void OnMahdChanged();
    partial void OnMakhChanging(string value);
    partial void OnMakhChanged();
    partial void OnTenkhChanging(string value);
    partial void OnTenkhChanged();
    partial void OnidNguoibanChanging(string value);
    partial void OnidNguoibanChanged();
    partial void OnNgaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapChanged();
    #endregion
		
		public Hoadon()
		{
			this._ChiTietHoaDon = default(EntityRef<ChiTietHoaDon>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahd", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahd
		{
			get
			{
				return this._Mahd;
			}
			set
			{
				if ((this._Mahd != value))
				{
					if (this._ChiTietHoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahdChanging(value);
					this.SendPropertyChanging();
					this._Mahd = value;
					this.SendPropertyChanged("Mahd");
					this.OnMahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkh", DbType="NVarChar(50)")]
		public string Tenkh
		{
			get
			{
				return this._Tenkh;
			}
			set
			{
				if ((this._Tenkh != value))
				{
					this.OnTenkhChanging(value);
					this.SendPropertyChanging();
					this._Tenkh = value;
					this.SendPropertyChanged("Tenkh");
					this.OnTenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNguoiban", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string idNguoiban
		{
			get
			{
				return this._idNguoiban;
			}
			set
			{
				if ((this._idNguoiban != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNguoibanChanging(value);
					this.SendPropertyChanging();
					this._idNguoiban = value;
					this.SendPropertyChanged("idNguoiban");
					this.OnidNguoibanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this.OnNgaylapChanging(value);
					this.SendPropertyChanging();
					this._Ngaylap = value;
					this.SendPropertyChanged("Ngaylap");
					this.OnNgaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietHoaDon_Hoadon", Storage="_ChiTietHoaDon", ThisKey="Mahd", OtherKey="Mahd", IsForeignKey=true)]
		public ChiTietHoaDon ChiTietHoaDon
		{
			get
			{
				return this._ChiTietHoaDon.Entity;
			}
			set
			{
				ChiTietHoaDon previousValue = this._ChiTietHoaDon.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietHoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietHoaDon.Entity = null;
						previousValue.Hoadon = null;
					}
					this._ChiTietHoaDon.Entity = value;
					if ((value != null))
					{
						value.Hoadon = this;
						this._Mahd = value.Mahd;
					}
					else
					{
						this._Mahd = default(string);
					}
					this.SendPropertyChanged("ChiTietHoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Hoadon", Storage="_KhachHang", ThisKey="Makh", OtherKey="Makh", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.Hoadons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.Hoadons.Add(this);
						this._Makh = value.Makh;
					}
					else
					{
						this._Makh = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Hoadon", Storage="_NhanVien", ThisKey="idNguoiban", OtherKey="ID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.Hoadons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.Hoadons.Add(this);
						this._idNguoiban = value.ID;
					}
					else
					{
						this._idNguoiban = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Makh;
		
		private string _Tenkh;
		
		private string _Sdt;
		
		private System.Nullable<bool> _Gioitinh;
		
		private string _Diachi;
		
		private EntitySet<Hoadon> _Hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakhChanging(string value);
    partial void OnMakhChanged();
    partial void OnTenkhChanging(string value);
    partial void OnTenkhChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    #endregion
		
		public KhachHang()
		{
			this._Hoadons = new EntitySet<Hoadon>(new Action<Hoadon>(this.attach_Hoadons), new Action<Hoadon>(this.detach_Hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkh", DbType="NVarChar(50)")]
		public string Tenkh
		{
			get
			{
				return this._Tenkh;
			}
			set
			{
				if ((this._Tenkh != value))
				{
					this.OnTenkhChanging(value);
					this.SendPropertyChanging();
					this._Tenkh = value;
					this.SendPropertyChanged("Tenkh");
					this.OnTenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(10)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Hoadon", Storage="_Hoadons", ThisKey="Makh", OtherKey="Makh")]
		public EntitySet<Hoadon> Hoadons
		{
			get
			{
				return this._Hoadons;
			}
			set
			{
				this._Hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mancc;
		
		private string _Tenncc;
		
		private string _Mahang;
		
		private string _Tenhang;
		
		private string _Diachi;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Dongia;
		
		private System.Nullable<decimal> _Thanhtien;
		
		private EntitySet<Doanhthu> _Doanhthus;
		
		private EntityRef<Hanghoa> _Hanghoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManccChanging(string value);
    partial void OnManccChanged();
    partial void OnTennccChanging(string value);
    partial void OnTennccChanged();
    partial void OnMahangChanging(string value);
    partial void OnMahangChanged();
    partial void OnTenhangChanging(string value);
    partial void OnTenhangChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnDongiaChanging(System.Nullable<decimal> value);
    partial void OnDongiaChanged();
    partial void OnThanhtienChanging(System.Nullable<decimal> value);
    partial void OnThanhtienChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._Doanhthus = new EntitySet<Doanhthu>(new Action<Doanhthu>(this.attach_Doanhthus), new Action<Doanhthu>(this.detach_Doanhthus));
			this._Hanghoa = default(EntityRef<Hanghoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mancc", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mancc
		{
			get
			{
				return this._Mancc;
			}
			set
			{
				if ((this._Mancc != value))
				{
					this.OnManccChanging(value);
					this.SendPropertyChanging();
					this._Mancc = value;
					this.SendPropertyChanged("Mancc");
					this.OnManccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenncc", DbType="NVarChar(50)")]
		public string Tenncc
		{
			get
			{
				return this._Tenncc;
			}
			set
			{
				if ((this._Tenncc != value))
				{
					this.OnTennccChanging(value);
					this.SendPropertyChanging();
					this._Tenncc = value;
					this.SendPropertyChanged("Tenncc");
					this.OnTennccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					if (this._Hanghoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhang", DbType="NVarChar(50)")]
		public string Tenhang
		{
			get
			{
				return this._Tenhang;
			}
			set
			{
				if ((this._Tenhang != value))
				{
					this.OnTenhangChanging(value);
					this.SendPropertyChanging();
					this._Tenhang = value;
					this.SendPropertyChanged("Tenhang");
					this.OnTenhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Money")]
		public System.Nullable<decimal> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtien", DbType="Money")]
		public System.Nullable<decimal> Thanhtien
		{
			get
			{
				return this._Thanhtien;
			}
			set
			{
				if ((this._Thanhtien != value))
				{
					this.OnThanhtienChanging(value);
					this.SendPropertyChanging();
					this._Thanhtien = value;
					this.SendPropertyChanged("Thanhtien");
					this.OnThanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Doanhthu", Storage="_Doanhthus", ThisKey="Mancc", OtherKey="Mancc")]
		public EntitySet<Doanhthu> Doanhthus
		{
			get
			{
				return this._Doanhthus;
			}
			set
			{
				this._Doanhthus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanghoa_NhaCungCap", Storage="_Hanghoa", ThisKey="Mahang", OtherKey="Mahang", IsForeignKey=true)]
		public Hanghoa Hanghoa
		{
			get
			{
				return this._Hanghoa.Entity;
			}
			set
			{
				Hanghoa previousValue = this._Hanghoa.Entity;
				if (((previousValue != value) 
							|| (this._Hanghoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hanghoa.Entity = null;
						previousValue.NhaCungCaps.Remove(this);
					}
					this._Hanghoa.Entity = value;
					if ((value != null))
					{
						value.NhaCungCaps.Add(this);
						this._Mahang = value.Mahang;
					}
					else
					{
						this._Mahang = default(string);
					}
					this.SendPropertyChanged("Hanghoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Doanhthus(Doanhthu entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_Doanhthus(Doanhthu entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Hoten;
		
		private string _Gioitinh;
		
		private System.Nullable<System.DateTime> _Namsinh;
		
		private System.Nullable<int> _Socmt;
		
		private System.Nullable<int> _Sdt;
		
		private string _Diachi;
		
		private string _Chucvu;
		
		private string _iduser;
		
		private EntitySet<Hoadon> _Hoadons;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnNamsinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNamsinhChanged();
    partial void OnSocmtChanging(System.Nullable<int> value);
    partial void OnSocmtChanged();
    partial void OnSdtChanging(System.Nullable<int> value);
    partial void OnSdtChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    partial void OniduserChanging(string value);
    partial void OniduserChanged();
    #endregion
		
		public NhanVien()
		{
			this._Hoadons = new EntitySet<Hoadon>(new Action<Hoadon>(this.attach_Hoadons), new Action<Hoadon>(this.detach_Hoadons));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namsinh", DbType="Date")]
		public System.Nullable<System.DateTime> Namsinh
		{
			get
			{
				return this._Namsinh;
			}
			set
			{
				if ((this._Namsinh != value))
				{
					this.OnNamsinhChanging(value);
					this.SendPropertyChanging();
					this._Namsinh = value;
					this.SendPropertyChanged("Namsinh");
					this.OnNamsinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socmt", DbType="Int")]
		public System.Nullable<int> Socmt
		{
			get
			{
				return this._Socmt;
			}
			set
			{
				if ((this._Socmt != value))
				{
					this.OnSocmtChanging(value);
					this.SendPropertyChanging();
					this._Socmt = value;
					this.SendPropertyChanged("Socmt");
					this.OnSocmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="Int")]
		public System.Nullable<int> Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(20)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iduser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string iduser
		{
			get
			{
				return this._iduser;
			}
			set
			{
				if ((this._iduser != value))
				{
					this.OniduserChanging(value);
					this.SendPropertyChanging();
					this._iduser = value;
					this.SendPropertyChanged("iduser");
					this.OniduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Hoadon", Storage="_Hoadons", ThisKey="ID", OtherKey="idNguoiban")]
		public EntitySet<Hoadon> Hoadons
		{
			get
			{
				return this._Hoadons;
			}
			set
			{
				this._Hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_NhanVien", Storage="_User", ThisKey="ID", OtherKey="username", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.NhanVien = null;
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
						this._ID = value.username;
					}
					else
					{
						this._ID = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private int _pass;
		
		private string _chuthich;
		
		private string _iduser;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpassChanging(int value);
    partial void OnpassChanged();
    partial void OnchuthichChanging(string value);
    partial void OnchuthichChanged();
    partial void OniduserChanging(string value);
    partial void OniduserChanged();
    #endregion
		
		public User()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="Int NOT NULL")]
		public int pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuthich", DbType="NVarChar(100)")]
		public string chuthich
		{
			get
			{
				return this._chuthich;
			}
			set
			{
				if ((this._chuthich != value))
				{
					this.OnchuthichChanging(value);
					this.SendPropertyChanging();
					this._chuthich = value;
					this.SendPropertyChanged("chuthich");
					this.OnchuthichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iduser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string iduser
		{
			get
			{
				return this._iduser;
			}
			set
			{
				if ((this._iduser != value))
				{
					this.OniduserChanging(value);
					this.SendPropertyChanging();
					this._iduser = value;
					this.SendPropertyChanged("iduser");
					this.OniduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_NhanVien", Storage="_NhanVien", ThisKey="username", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.User = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.User = this;
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
